name: CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKER_USER }}/arthuru0_devops:latest .

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USER }}/arthuru0_devops:latest
